#Include "macOS-navigation.ahk"
#Include "macOS-accented-characters.ahk"
#Include "ignored-windows-shortcuts.ahk"
#Include "macOS-hot-corners.ahk"
#Include "app-shortcuts.ahk"
#Include "wording-shortcuts.ahk"